

CODIGOS_SOLICITUDES = {
    '72': 'PAGO DE SERVICIOS',
    '00': 'COMPRA',
    '02': 'CONSULTA SALDO (POS)',
    '05': 'EXTRACCION EFECTIVO (ATM)',
    '10': 'CONSULTA SALDO (ATM)',
    '01': 'ADELANTO EFECTIVO (POS)'
}


CODIGOS_RESPUESTAS = {
    '00': 'APROBADA',
    '06': 'ERROR DE SISTEMA',
    '12': 'TRANSACCION INVALIDA',
    '30': 'ERROR DE FORMATO DE PAQUETE',
    '36': 'TARJETA / CUENTA BLOQUEADA POR LA ENTIDAD',
    '51': 'NO APROBADA - INSUF.DE FONDOS',
    '52': 'NO APROBADA - NO EXISTE CUENTA CORRIENTE',
    '53': 'NO APROBADA - NO EXISTE CUENTA DE AHORRO',
    '96': 'EMISOR DE LA TARJETA FUERA DE SERVICIO'
}

