INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ('BEP', 'OPE', 0, 'COMPRA', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ('BEP', 'OPE', 1, 'ADELANTO EFECTIVO (POS)', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ('BEP', 'OPE', 2, 'CONSULTA SALDO (POS)', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ('BEP', 'OPE', 5, 'EXTRACCION EFECTIVO (ATM)', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ('BEP', 'OPE', 10, 'CONSULTA SALDO (ATM)', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ('BEP', 'OPE', 72, 'PAGO DE SERVICIOS', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 0, 'APROBADA', 'ACT' );
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 6, 'ERROR DEL SISTEMA', 'ACT' );
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 12, 'TRANSACCION INVALIDA', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 30, 'ERROR DE FORMATO DEL PAQUETE', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 36, 'TARJETA/CUENTA BLOQUEADA POR LA ENTIDAD', 'ACT' );
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 51, 'NO APROBADA - INSUFICIENCIA DE FONDOS', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 52, 'NO APROBADA - NO EXISTE CUENTA CORRIENTE', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 53, 'NO APROBADA - NO EXISTE CUENTA DE AHORRO', 'ACT');
INSERT INTO tccodopr ("TCOS_PROCESO", "TCOS_TIPCOD", "TCOS_CODIGO", "TCOS_DESCRIPCION", "TCOS_ESTADO") VALUES ( 'BEP', 'RET', 96, 'EMISOR DE TARJETA FUERA DE SERVICIO', 'ACT');



INSERT INTO tctipo ("TCTI_TIPO", "TCTI_NOMBR", "TCTI_COMIS", "TCTI_INTER", "TCTI_MONED", "TCTI_COTIZ") VALUES ('TD1', 'SOCIO - CENCOPAN DEBITO', 1.00, 1.00, 1, 1)
